version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: example-database
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - pg-network
    volumes:
      - "pg-data:/var/lib/postgresql/data:rw"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    env_file:
      - .env
    ports:
      - "8080:80"
    networks:
      - pg-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  pg-network:

volumes:
  pg-data:
  pgadmin-data: